
#define TITRE "TEST CARTE D855ED2"
#define ATTENTE "ATTENTE DEMARRAGE"
#define CONFORME "TEST CONFORME"
#define NON_CONFORME "TEST NON CONFORME"
#define LIGNE_VIDE ""
#define OK_REQUEST "APPUYER SUR OK"
#define PROGRESS "TEST EN COURS"
#define BOARD_REQUEST "POSITIONNER CARTE"
#define BOARD_REF "PLACER CARTE REF"
#define ACQ "ATTENTE ACQUITTEMENT"
#define FIN "FIN DE TEST"
#define ANSWER "APPUYER SUR OK/NOK"


void displayManager(char s1[], char s2[], char s3[], char s4[]);